### ISSUE TITLE
how about use libnetwork to provide consistent programming interface for network part

### ISSUE THREAD

**Issue by AdoHe** [cloudfoundry-incubator/guardian#3]
FYI. for guardian we have Kawasaki, this amazing network, but we can just use bridge now, I think we can use some model of libnetwork  and provide our own implementation.

**Comment by goonzoid** [comment]
Hi @AdoHe - I think you may be interested in this proposal on the cf-dev mailing list about using libnetwork to implement container to container networking in Diego! 

You can see the thread here: https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/message/3E7QRIFLC32QK3Q7LMR7FDZPBYLM2BXV/

We'll close this for now, since the discussion is happening on the mailing list.
