### ISSUE TITLE
Is there a roadmap of guardian?

### ISSUE THREAD

**Issue by zenlinTechnofreak** [cloudfoundry-incubator/guardian#6]
Hi,
    It is very nice to get the infomation of the Garden project is going to transition from it’s own backend for Linux containers to using runC from the Open Container Initiative.
I am developing oci testing project [OCT](http://github.com/huawei-openlab/oct) which aims to testing whether the container runtime is compliant to opencontainers/specs. The project is in the [OCI/roadmap](https://github.com/opencontainers/specs/blob/master/ROADMAP.md) 1.0 of OCI now.
So, my question is , is there a roadmap of guardian?
If it does have,  we are going to do supporting docker(using guardian to run OCI bundle) in OCT(see [OCT/roadmap](https://github.com/huawei-openlab/oct/blob/master/ROADMAP.md))
Any information about plan of guardian, please help to let me know.
Thanks very much.

**Comment by julz** [comment]
Hi @zenlinTechnofreak - our first priority is to get enough of the existing Garden API implemented in the Guardian backend to allow Cloud Foundry to swap over to this backend. We're planning to use runC as the low level container runtime initially (although we hope to support others over time, of course). I'm not sure it makes sense to test Guardian via OCT since you'd just be testing runC, but maybe you could give more detail about what you're trying to do?

It might be most efficient if we organise a hangout where we can talk through stuff and see how we could help each other. Feel free to reach out via email to myself and @goonzoid if you'd like to do that!

**Comment by zenlinTechnofreak** [comment]
@julz 
OCT in OCI is going to validate runtime of docker. And the testing of docker's compliance to specs have to base on OCI bundle.
The blocked thing is docker  cannot be running with OCI bundle directly but docker image.
It is a good news for guardian to connect docker and runc,
Therefore, once guardian finishing the feature of supporting runc, OCT can support validating docker immediately.
That is the reason why I want to get the roadmap/plan of guardian.
And of cause, I am planing to involve myself into guardian.
Thanks.
